<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="81620" started-at="2020-12-04T06:20:39Z" finished-at="2020-12-04T06:22:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="81620" started-at="2020-12-04T06:20:39Z" finished-at="2020-12-04T06:22:00Z">
      <class name="TestScripts.searchSubject">
        <test-method status="PASS" signature="setUP()[pri:0, instance:TestScripts.searchSubject@6e171cd7]" name="setUP" is-config="true" duration-ms="12907" started-at="2020-12-04T11:50:26Z" finished-at="2020-12-04T11:50:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="PASS" signature="setup()[pri:0, instance:TestScripts.searchSubject@6e171cd7]" name="setup" is-config="true" duration-ms="340" started-at="2020-12-04T11:50:39Z" finished-at="2020-12-04T11:50:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="searchSubjectTest()[pri:0, instance:TestScripts.searchSubject@6e171cd7]" name="searchSubjectTest" duration-ms="81243" started-at="2020-12-04T11:50:39Z" finished-at="2020-12-04T11:52:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [test] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [test] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at TestScripts.StudentTest.viewClassroomInfo(StudentTest.java:50)
	at TestScripts.searchSubject.searchSubjectTest(searchSubject.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchSubjectTest -->
      </class> <!-- TestScripts.searchSubject -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
